// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSurveyBuilder.Server.Data;

#nullable disable

namespace SmartSurveyBuilder.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260610031154_SyncChanges")]
    partial class SyncChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.AnalyticsModule.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<string>("FileName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("SurveyId")
                        .HasColumnType("int");

                    b.HasKey("ReportId")
                        .HasName("PK__Reports__D5BD48055963D08B");

                    b.HasIndex("SurveyId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.AuthModule.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.AuthModule.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1A05DEE2D2");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.AuthModule.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C047EFDF8");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.LogicModule.Models.QuestionLogic", b =>
                {
                    b.Property<int>("LogicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogicId"));

                    b.Property<string>("ActionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExpectedAnswer")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("OperatorType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SourceQuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("TargetQuestionId")
                        .HasColumnType("int");

                    b.HasKey("LogicId")
                        .HasName("PK__Question__4A718C1DCB0A58AA");

                    b.HasIndex("SourceQuestionId");

                    b.HasIndex("TargetQuestionId");

                    b.ToTable("QuestionLogics");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.NotificationModule.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E12A7A5E79F");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.QuestionModule.Models.Option", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionId"));

                    b.Property<string>("OptionText")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("OptionId")
                        .HasName("PK__Options__92C7A1FF38260CDF");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.QuestionModule.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SurveyId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId")
                        .HasName("PK__Question__0DC06FAC4265F3EE");

                    b.HasIndex("SurveyId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.ResponseModule.Models.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerId"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("ResponseId")
                        .HasColumnType("int");

                    b.HasKey("AnswerId")
                        .HasName("PK__Answers__D48250045FF4E766");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ResponseId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.ResponseModule.Models.Response", b =>
                {
                    b.Property<int>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResponseId"));

                    b.Property<string>("RespondentEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("SurveyId")
                        .HasColumnType("int");

                    b.HasKey("ResponseId")
                        .HasName("PK__Response__1AAA646C7E78E5FF");

                    b.HasIndex("SurveyId");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.SurveyModule.Models.Survey", b =>
                {
                    b.Property<int>("SurveyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurveyId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SurveyId")
                        .HasName("PK__Surveys__A5481F7DA88FA9E8");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.SurveyModule.Models.SurveySettings", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingId"));

                    b.Property<bool?>("AllowMultipleResponses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("RequireLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("ShowProgressBar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShuffleQuestions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("SurveyId")
                        .HasColumnType("int");

                    b.HasKey("SettingId")
                        .HasName("PK__SurveySe__54372B1D8C5504F7");

                    b.HasIndex("SurveyId");

                    b.ToTable("SurveySettings");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.UserModule.Models.UserProfile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsPublicProfile")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("SmsNotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.AnalyticsModule.Models.Report", b =>
                {
                    b.HasOne("SmartSurveyBuilder.Server.Modules.SurveyModule.Models.Survey", "Survey")
                        .WithMany("Reports")
                        .HasForeignKey("SurveyId")
                        .HasConstraintName("FK__Reports__SurveyI__76969D2E");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.AuthModule.Models.RefreshToken", b =>
                {
                    b.HasOne("SmartSurveyBuilder.Server.Modules.AuthModule.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.LogicModule.Models.QuestionLogic", b =>
                {
                    b.HasOne("SmartSurveyBuilder.Server.Modules.QuestionModule.Models.Question", "SourceQuestion")
                        .WithMany("QuestionLogicSourceQuestions")
                        .HasForeignKey("SourceQuestionId")
                        .HasConstraintName("FK__QuestionL__Sourc__656C112C");

                    b.HasOne("SmartSurveyBuilder.Server.Modules.QuestionModule.Models.Question", "TargetQuestion")
                        .WithMany("QuestionLogicTargetQuestions")
                        .HasForeignKey("TargetQuestionId")
                        .HasConstraintName("FK__QuestionL__Targe__66603565");

                    b.Navigation("SourceQuestion");

                    b.Navigation("TargetQuestion");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.NotificationModule.Models.Notification", b =>
                {
                    b.HasOne("SmartSurveyBuilder.Server.Modules.AuthModule.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Notificat__UserI__72C60C4A");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.QuestionModule.Models.Option", b =>
                {
                    b.HasOne("SmartSurveyBuilder.Server.Modules.QuestionModule.Models.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("FK__Options__Questio__628FA481");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.QuestionModule.Models.Question", b =>
                {
                    b.HasOne("SmartSurveyBuilder.Server.Modules.SurveyModule.Models.Survey", "Survey")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .HasConstraintName("FK__Questions__Surve__5FB337D6");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.ResponseModule.Models.Answer", b =>
                {
                    b.HasOne("SmartSurveyBuilder.Server.Modules.QuestionModule.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("FK__Answers__Questio__6E01572D");

                    b.HasOne("SmartSurveyBuilder.Server.Modules.ResponseModule.Models.Response", "Response")
                        .WithMany("Answers")
                        .HasForeignKey("ResponseId")
                        .HasConstraintName("FK__Answers__Respons__6D0D32F4");

                    b.Navigation("Question");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.ResponseModule.Models.Response", b =>
                {
                    b.HasOne("SmartSurveyBuilder.Server.Modules.SurveyModule.Models.Survey", "Survey")
                        .WithMany("Responses")
                        .HasForeignKey("SurveyId")
                        .HasConstraintName("FK__Responses__Surve__6A30C649");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.SurveyModule.Models.Survey", b =>
                {
                    b.HasOne("SmartSurveyBuilder.Server.Modules.AuthModule.Models.User", "CreatedByNavigation")
                        .WithMany("Surveys")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Surveys__Created__5441852A");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.SurveyModule.Models.SurveySettings", b =>
                {
                    b.HasOne("SmartSurveyBuilder.Server.Modules.SurveyModule.Models.Survey", "Survey")
                        .WithMany("SurveySettings")
                        .HasForeignKey("SurveyId")
                        .HasConstraintName("FK__SurveySet__Surve__5AEE82B9");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.UserModule.Models.UserProfile", b =>
                {
                    b.HasOne("SmartSurveyBuilder.Server.Modules.AuthModule.Models.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("SmartSurveyBuilder.Server.Modules.UserModule.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.AuthModule.Models.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Surveys");

                    b.Navigation("UserProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.QuestionModule.Models.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Options");

                    b.Navigation("QuestionLogicSourceQuestions");

                    b.Navigation("QuestionLogicTargetQuestions");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.ResponseModule.Models.Response", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("SmartSurveyBuilder.Server.Modules.SurveyModule.Models.Survey", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Reports");

                    b.Navigation("Responses");

                    b.Navigation("SurveySettings");
                });
#pragma warning restore 612, 618
        }
    }
}
